[project]
name = "bi-hub-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "databricks-sdk>=0.67.0",
    "psycopg2>=2.9.10",
]
